"""
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
"""


def num_divisors(n):
    divisors = set()
    d1 = 1
    d2 = n
    while d2 > d1:
        if d1*d2 == n:
            divisors.add(d1)
            divisors.add(d2)
        d1 += 1
        d2 = int(n/d1)
    return len(divisors)

n = 1
inc = 2

while num_divisors(n) < 500:
    n = n + inc
    inc += 1
print(n)