"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""


tn = 286
pn = 166
hn = 144

def Tn(n):
    return int(n*(n+1)/2)

def Pn(n):
    return int(n*(3*n-1)/2)

def Hn(n):
    return int(n*(2*n-1))

def answer(tn,pn,hn):
    T = Tn(tn)
    P = Pn(pn)
    H = Hn(hn)
    while T != P or T != H or P != H:
        #update the minimal value
        U = min(T,P,H)
        if U == T:
            tn += 1
            T = Tn(tn)
        elif U == H:
            hn += 1
            H = Hn(hn)
        else: #U == P
            pn += 1
            P = Pn(pn)
    print(T)
    
if __name__ == "__main__":
    print(answer(tn,pn,hn))